language: c
compiler:
    - gcc
    - clang
script: ./platform/linux/build_and_install SKIP
notifications:
    email:
        recipients:
            - alexsimonjones@gmail.com
            - dragan.glumac@gmail.com
        on_sucess: [never]
        on_failure: [always] # default: always
