language: c
compiler:
    - gcc
    - clang
script: ./configure && make setup && cd test && ./run_tests && cd ../ && make teardown && make
notifications:
    email:
        recipients:
            - alexsimonjones@gmail.com
            - dragan.glumac@gmail.com
        on_sucess: [never]
        on_failure: [always] # default: always
