language: c
compiler:
    - gcc
    - clang
script: cmake . && make && sudo make install
notifications:
    email:
        recipients:
            - alexsimonjones@gmail.com
            - dragan.glumac@gmail.com
        on_sucess: [never]
        on_failure: [always] # default: always
