language: c
compiler:
    - gcc
    - clang
script:  echo "yes" | sudo add-apt-repository ppa:kalakris/cmake && sudo apt-get install cmake && cmake . && make && ./test/run_tests
notifications:
    email:
        recipients:
            - alexsimonjones@gmail.com
            - dragan.glumac@gmail.com
        on_sucess: [never]
        on_failure: [always] # default: always
    irc:
        channels:
            - "chat.freenode.net#jnxlibc"
    on_sucess: [always]
    on_failure: [always] # default: always
