language: c
compiler:
    - gcc
    - clang
script: cd test && ./run_tests
notifications:
    email:
        recipients:
            - alexsimonjones@gmail.com
            - dragan.glumac@gmail.com
        on_sucess: [never]
        on_failure: [always] # default: always
        notifications:
    irc:
        channels: "irc.freenode.org#jnxlibc"
    on_success: change
    on_failure: change
