language: c
compiler:
    - gcc
    - clang
before_script: cmake . && make
script: make
notifications:
    email:
        recipients:
            - alexsimonjones@gmail.com
            - dragan.glumac@gmail.com
        on_sucess: [never]
        on_failure: [always] # default: always
    irc:
        channels:
            - "chat.freenode.net#jnxlibc"
    on_sucess: [always]
    on_failure: [always] # default: always
